package org.exception;

public class Exception {
	
      public static void main(String[] args) {

    	  try
          {
           System.out.printf("1");
            int data = 5 / 0;
          }
         catch(ArithmeticException e)
          {
         System.out.printf("2");
         System.exit(0);
           }
         finally
            {
          System.out.printf("3");
            }
         System.out.printf("4");
           }
            }
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	  
    	 // try {
           //   System.out.printf("1");
             // int sum = 9 / 0;
               
           //   System.out.printf("2");
               
         //  } catch (ArithmeticException e) {
             //  System.out.printf("3");
           
         //  } finally {
           //    System.out.printf("5");
       //    }
     //  }
   //}  
    		
    		
    	 
          
          
     


